### ISSUE TITLE
smush.it url

### ISSUE THREAD

**Issue by jacqueminv** [obeattie/smooshy-py#3]
The url used to call smush.it is incorrect at the moment.

Use instead the one from the ruby gem: http://ws1.adq.ac4.yahoo.com/ysmush.it/ws.php

By the way smoosher.py cannot be run in command line for 2 reasons:

no shebang at the top (if it is intended, please put in the doc)
if **name** == "**main**": not included

**Comment by obeattie** [comment]
URL fixed by merge of 5790d2f6b38d853a6482d0af0952855123d54f8a
Shebang/script stuff fixed in 2872e6825fb07acdedd2fbe9e9c6169eca8d9e32
